### ISSUE TITLE
Burner Chains vs Tutorials

### ISSUE THREAD

**Issue by jackzampolin** [allinbits/burner-chains#12]
What is the difference between burner chains and tutorials and should they live in the same repo?

cc @marbar3778 @okwme

**Comment by okwme** [comment]
good question.

I kind of imagine the tutorial repo a place where markdown is compiled into a vuepress website that integrates code snippets from source and any other interactivity we may be able to incorporate.

It seems like if we run an actual chain it should have its own repo so that all the necessary chain specific information can be in the same place (simimlar to the gaia repo). I imagine these repos under the cosmos name as part of a mono-repo or as separate repos. Within this repo is where a README would point to various tutorials that explain how to use or interact with the burner chain. These tutorials would naturally live in the tutorial repo and have all the features of other tutorials (and be located under the same tutorial domain name / root path).

I think this repo should be used to propose and discuss features of burner chains, as well as keep the current status and links to the actual chain repos as they develop. A certain aspect of this repo should be reproduced within the Awesome repo under a burner chain eventually. This repo is for / by allinbits and so should be used for internal discussion and resource allocation. The awesome repo is meant to be outward facing.

**Comment by jackzampolin** [comment]
Thank you for the explanation @okwme! This addressed my concerns. What is actionable here? Do we need to make immediate changes to other repos? What can we do to move to this proposed structure.

**Comment by okwme** [comment]
I've made a proposal for how to organize burner chains at #14 which addresses part of this issue but actually brings up a larger question about the future, direction and goals of tutorials in general. I think it deserves it's own call to discuss. Let's close this and schedule a time to meet and talk about it with higher bandwidth than a github issue.
